name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.idea/**'
      - '.run/**'
      - '**/*.iml'
      - '**/*.md'
      - '**/.editorconfig'
      - '**/.gitattributes'
      - '**/.gitignore'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.run/**'
      - '**/*.iml'
      - '**/*.md'
      - '**/.editorconfig'
      - '**/.gitattributes'
      - '**/.gitignore'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome', 'firefox', 'edge' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Firefox
      if: ${{ matrix.browser == 'firefox' }}
      uses: browser-actions/setup-firefox@latest
    - name: Setup Edge
      if: ${{ matrix.browser == 'edge' }}
      uses: browser-actions/setup-edge@latest
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run tests in ${{ matrix.browser }}
      run: ./gradlew ${{ matrix.browser }} -Dheadless=true

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report-${{ matrix.browser }}
        retention-days: 7
        path: |
          **/build/reports
          **/build/test-results

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    timeout-minutes: 10
    needs: [build]
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: 🤖 Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          target: minor
          merge-method: rebase
